CREATE SCHEMA WEEK2Assignment


CREATE TABLE WEEK2Assignment.Customers
(ID int PRIMARY KEY NOT NULL, 
 Firstname varchar(50), 
 Lastname varchar(50), 
 CardNumber varchar(16)
 )

CREATE TABLE WEEK2Assignment.Products
(ID int PRIMARY KEY NOT NULL, 
 Name varchar(50), 
 Price int
 )

CREATE TABLE WEEK2Assignment.Orders
(ID int PRIMARY KEY, 
 ProductID int FOREIGN KEY REFERENCES WEEK2Assignment.Products(ID), 
 CustomerID int FOREIGN KEY REFERENCES WEEK2Assignment.Customers(ID)
)


-- I was trying to create a schema with these tables but couldnt figure out how to reference them correctly.
-- I tried doing things like	INSERT INTO WEEK2Assignment.Customers(data) but it doesnt work properly...


-- 1. Add at least 3 records into each table

INSERT INTO Customers (ID, Firstname, Lastname, CardNumber)
VALUES (1, 'Morgan', 'Hay', '1234567812345678');

INSERT INTO Customers (ID, Firstname, Lastname, CardNumber)
VALUES (2, 'Norgan', 'May', '1234567881234567');

INSERT INTO Customers (ID, Firstname, Lastname, CardNumber)
VALUES (3, 'Horgan', 'Nay', '1234567871234567');



INSERT INTO Products (ID, Name, Price)
VALUES (101, 'Samsung', 250)

INSERT INTO Products (ID, Name, Price)
VALUES (102, 'LG', 225)

INSERT INTO Products (ID, Name, Price)
VALUES (103, 'Motorola', 175)



INSERT INTO Orders (ID, ProductID, CustomerID)
VALUES (1001, 101, 1)

INSERT INTO Orders (ID, ProductID, CustomerID)
VALUES (1002, 103, 1)

INSERT INTO Orders (ID, ProductID, CustomerID)
VALUES (1003, 102, 3)


-- 2. Add product iPhone priced at $200

INSERT INTO Products (ID, Name, Price)
VALUES (104, 'iPhone', 200)


-- 3. Add customer Tina Smith

INSERT INTO Customers (ID, Firstname, Lastname, CardNumber)
VALUES (4, 'Tina', 'Smith', '1234567861234567')


-- 4. Create order for Tina Smith bought an iPhone

INSERT INTO Orders (ID, ProductID, CustomerID)
VALUES (1004, 104, 4)



-- 5. Report all orders by Tina Smith

SELECT *
FROM Orders RIGHT JOIN Customers ON Orders.CustomerID = Customers.ID
WHERE Customers.Firstname = 'Tina' AND Customers.Lastname = 'Smith'


-- 6. Report all revenue generated by sales of iPhone

SELECT (COUNT(*)*200)
FROM Orders LEFT JOIN Products ON Orders.ProductID = Products.ID
WHERE Products.Name = 'iPhone'


-- 7. Increase the price of iPhone to $250

UPDATE Products
SET Price = 250
WHERE Name = 'iPhone'